jobs:
  - name: lifecycle-unit
    plan:
      - get: lifecycle-repo
        trigger: true
        version: every
      - get: pipeline-repo
      - task: run-unit-tests
        privileged: true
        file: pipeline-repo/tasks/run-lifecycle-unit/task.yml

  - name: lifecycle-unit
    plan:
      - get: pack-repo
        trigger: true
        version: every
      - get: pipeline-repo
      - task: run-unit-tests
        privileged: true
        file: pipeline-repo/tasks/run-pack-unit/task.yml
