jobs:
  - name: lifecycle-unit
    plan:
      - get: lifecycle-repo
        trigger: true
        version: every
      - get: pipeline-repo
      - task: run-unit-tests
        privileged: true
        file: pipeline-repo/tasks/run-lifecycle-unit/task.yml
      - put: packs-base-image
        params:
          import_file: packs-build/built-lifecyle-images/base.tar
      - put: packs-run-image
        params:
          import_file: packs-build/built-lifecyle-images/run.tar
      - put: packs-build-image
        params:
          import_file: packs-build/built-lifecyle-images/build.tar
      - put: packs-samples-image
        params:
          import_file: packs-build/built-lifecyle-images/samples.tar

  - name: pack-unit
    plan:
      - get: pack-repo
        trigger: true
        version: every
      - get: pipeline-repo
      - task: run-unit-tests
        privileged: true
        file: pipeline-repo/tasks/run-pack-unit/task.yml

  - name: acceptance
    plan:
      - get: pack-repo
      - get: pipeline-repo
      - get: packs-samples-image
        passed: [lifecycle-unit]
      - task: acceptance
        privileged: true
        file: pipeline-repo/tasks/run-acceptance/task.yml
