---
resources:
  - name: code
    type: git
    source:
      uri: https://github.com/buildpack/lifecycle

jobs:
  - name: test
    plan:
      - aggregate:
          - get: code
            params: {depth: 1}
            trigger: true
      - task: pack build
        privileged: true
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: concourse/docker-image-resource
          inputs:
            - name: code
          run:
            path: /bin/bash
            args:
              - -exc
              - |
                set +x
                source /opt/resource/common.sh
                start_docker 3 3
                set -x

                docker run -v /var/run/docker.sock:/var/run/docker.sock --network host -v $(pwd)/code:/workspace -w=/workspace golang go test -count=1 -parallel=1 -v ./...

                docker image ls