#!/usr/bin/env sh

set -o errexit
set -o pipefail
set -x

export GOPATH=$(pwd)/go

apk --no-cache add \
      bash \
      docker \
      jq \
      ca-certificates \
      xz

./pipeline-repo/tasks/run-lifecycle-unit/bashtime
