platform: linux
image_resource:
  type: docker-image
  source:
    repository: concourse/docker-image-resource

inputs:
  - name: pack-repo
  - name: pipeline-repo

run:
  path: pipeline-repo/tasks/run-pack-unit/run