#!/usr/bin/env bash

source pipeline-repo/scripts/common.sh

set -o errexit
set -o nounset
set -o pipefail

set -x

docker load -i packs-samples-image/image
docker tag "$(cat packs-samples-image/image-id)" "packs/samples:dev"

cd pack-repo
docker_run -e "PACK_TAG=dev" golang go test -v -count=1 -parallel=1 ./acceptance
