#!/usr/bin/env bash

source pipeline-repo/scripts/common.sh

set -o errexit
set -o nounset
set -o pipefail

set -x

cd lifecycle-repo

images/bin/build

cd ..

docker save packs/base -o built-lifecycle-images/base.tar
docker save packs/run -o built-lifecycle-images/run.tar
docker save packs/build -o built-lifecycle-images/build.tar
docker save packs/samples -o built-lifecycle-images/samples.tar