#!/usr/bin/env bash

source pipeline-repo/scripts/common.sh

set -o errexit
set -o nounset
set -o pipefail

set -x
version=$(cat ./lifecycle-image-version/version)

./lifecycle-repo/images/bin/build -v "$version"

for image in base run build samples; do
  docker tag "packs/$image:$version" "gcr.io:443/cf-build-service-dev-219913/packs/$image:$version"
  docker save "gcr.io:443/cf-build-service-dev-219913/packs/$image:$version" -o "built-lifecycle-images/$image.tar"
done

cp ./lifecycle-image-version/version built-lifecycle-images/tag
